name: Run .NET Tests

on:
  push:
    branches: lab_1
  pull_request:
    branches: lab_1

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore enterprise-development.sln

      - name: Build
        run: dotnet build enterprise-development.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test enterprise-development.sln --configuration Release --no-build